#!/bin/sh

# Check if script is run as root
if [ "$EUID" -eq 0 ]; then
  echo "This script should not be run as root. Please run it as a regular user." >&2
  exit 1
fi

# Enable read-write mode
sudo steamos-readonly disable

# Update system packages
sudo pacman -Syu --noconfirm

# Reinitialize pacman keys
sudo rm -rf /etc/pacman.d/gnupg/
sudo pacman-key --init
sudo pacman-key --populate

# Install packages from repo list
sudo pacman -S --needed - < pkglist-repo.txt --overwrite "*" --noconfirm

# Install git and base-devel
sudo pacman -S --needed git base-devel --noconfirm

# Clean up yay cache
sudo rm -r /home/deck/.cache/yay
sudo rm -r ./yay-bin

# Install yay from AUR
sudo pacman -S --needed git base-devel && \
  git clone https://aur.archlinux.org/yay-bin.git && \
  cd yay-bin && \
  git checkout cb857e898d7081a60cf8742d26247fd6a3c5443c && \
  yes | makepkg -si

# yay -Y --gendb
# yay -Syu --devel --noconfirm
# yay -Y --devel --save


# Install AUR packages from pkglist-aur.txt
for x in $(< pkglist-aur.txt); do yay -S $x --noconfirm; done

# Final success message
echo "Everything Installed correctly"
