#!/bin/sh

sudo steamos-readonly disable

sudo pacman -Syu --noconfirm

sudo rm -rf /etc/pacman.d/gnupg/ && sudo pacman-key --init && sudo pacman-key --populate

sudo pacman -S --needed - < pkglist-repo.txt --overwrite "*" --noconfirm

sudo pacman -S --needed git base-devel --noconfirm

sudo rm -r /home/deck/.cache/yay

sudo rm -r ./yay-bin

sudo pacman -S --needed git base-devel && \
git clone https://aur.archlinux.org/yay-bin.git && \
cd yay-bin && \
git checkout cb857e898d7081a60cf8742d26247fd6a3c5443c && \
yes | makepkg -si

# yay -Y --gendb
# yay -Syu --devel --noconfirm
# yay -Y --devel --save

for x in $(< pkglist-aur.txt); do yay -S  $x --noconfirm; done
